name: WebGL Build and Deploy

on:
  push:
    branches:
      - refactor_testing  # change this to your working branch

jobs:
  build-webgl:
    runs-on: ubuntu-latest
    name: Build WebGL and Deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Cache Library folder
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('**/ProjectSettings/ProjectVersion.txt') }}
          restore-keys: Library-${{ runner.os }}-
      - name: Request Unity Activation
        uses: game-ci/unity-activation@v1
        with:
          unityVersion: 2022.3.61f1
      - name: Build WebGL using GameCI
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: 2022.3.61f1
          targetPlatform: WebGL
          buildMethod: WebGLBuilder.BuildWebGL
    
      - name: Copy custom index.html before branch switch
        run: cp Assets/WebGLTemplate/index.html /tmp/custom_index.html
    
      - name: Prepare build branch
        run: |
          git config --global user.email "kidakwashe14@gmail.com"
          git config --global user.name "KeithChidamba"
          
          git fetch origin
          git switch -C webgl-build
          rm -rf *
          cp -r build/WebGL/* .
          rm -f index.html
          cp /tmp/custom_index.html index.html
          git add .
          git commit -m "Automated WebGL build with custom index.html"
          git push --force origin webgl-build
    
      - name: Check for build output
        run: |
          if [ ! -d "build/WebGL" ]; then
            echo "❌ WebGL build output missing"
            exit 1
          fi
